CREATE SEQUENCE HIBERNATE_SEQUECE START WITH 1 INCREMENT BY 1;
CREATE TABLE aluno (id integer generated by default as identity, nome VARCHAR(255), id_turma integer, PRIMARY KEY(id));
CREATE TABLE avaliacoes (conceito VARCHAR(255), disciplina_id integer NOT NULL, aluno_id integer NOT NULL, PRIMARY KEY(aluno_id, disciplina_id));
CREATE TABLE disciplina (id integer generated by default as identity, nome VARCHAR(255), PRIMARY KEY(id));
CREATE TABLE matricula (id_aluno integer NOT NULL, id_disciplina integer NOT NULL);
CREATE TABLE turma (id integer generated by default as identity, nome VARCHAR(255), PRIMARY KEY(id));

ALTER TABLE aluno add constraint FK6u9nh0rofks23793tl5j0f7v3 FOREIGN KEY (id_turma) REFERENCES turma;
ALTER TABLE avaliacoes add constraint FK84shm6tyijbbe8671yopxoiof FOREIGN KEY (disciplina_id) REFERENCES disciplina;
ALTER TABLE avaliacoes add constraint FK32qwgm9pwfboht1mgquke99ov FOREIGN KEY (aluno_id) REFERENCES aluno;
ALTER TABLE matricula add constraint FKn83nsklxp4qsqeqvlxdj5956j FOREIGN KEY (id_disciplina) REFERENCES disciplina;
ALTER TABLE matricula add constraint FK447ng01ewew6knrjl7gl4g65i FOREIGN KEY (id_aluno) REFERENCES aluno;
